### ISSUE TITLE
trying to compile in xcode 4.63/10.7.5

### ISSUE THREAD

**Issue by steeley** [admsyn/OFPlugin#6]
tried turning off ARC and enabling garbage collection (I think) to avoid compile error.
now just get 12 errors like this which stop the build.:
/Users/ian/Desktop/OFPlugin-master/OFPlugin/OFAddon.m:30:9: Use of undeclared identifier '_config'
